### ISSUE TITLE
Is it possible to change the output path to relative?

### ISSUE THREAD

**Issue by bdwain** [alwaysonlinetxm/rollup-plugin-img#1]
I'm trying to publish a library with this, but it seems like the path that is generated from the import statement looks like `var path = 'img/foo.svg';` 

Ideally, it would be `./img/foo.svg`, because when my app builds this, if it sees img/foo.svg, it's going to know to look for that in `node_modules/my_lib/es/img/foo.svg`, it'll only look where my app's build process knows about.

is it possible to add the ./ before the generated path? even if it requires an option to do this?

**Comment by alwaysonlinetxm** [comment]
@bdwain I have added a `_slash` option to meet your demand.  You can do as below now:

```JavaScript
image({
      hash: true,
      output: 'dist/images',
      _slash: true
    })
```

**Comment by bdwain** [comment]
Thanks!
